# Generated by Django 5.2.8 on 2025-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('almacenamiento', 'Almacenamiento'), ('despacho', 'Despacho'), ('transporte', 'Transporte'), ('uso', 'Uso')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_dispositivo', models.CharField(max_length=200)),
                ('lote', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=200)),
                ('que_ocurrio', models.CharField(choices=[('falla_calidad', 'Falla de calidad'), ('incidente', 'Incidente'), ('evento_adverso', 'Evento adverso'), ('casi_evento', 'Casi evento')], max_length=20)),
                ('descripcion', models.TextField()),
                ('accion_otro_texto', models.CharField(blank=True, max_length=300, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('acciones', models.ManyToManyField(blank=True, to='formulario.acciontomada')),
            ],
        ),
    ]
