# Generated by Django 5.2.8 on 2025-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='acciones',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='accion_otro_texto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AccionTomada',
        ),
        migrations.AddField(
            model_name='incidente',
            name='acciones',
            field=models.JSONField(default=list),
        ),
    ]
