# Generated by Django 5.2.8 on 2025-11-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_remove_incidente_acciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='que_ocurrio',
            field=models.CharField(choices=[('falla_calidad', 'Falla de calidad (envase, etiqueta, aspecto, vencimiento)'), ('incidente', 'Incidente (no causó daño, pero pudo causar)'), ('evento_adverso', 'Evento adverso (causó daño o riesgo de daño)'), ('casi_evento', 'Casi evento (error detectado a tiempo)')], max_length=20),
        ),
    ]
