# Generated by Django 5.2.8 on 2025-11-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_incidente_que_ocurrio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='accion_otro_texto',
        ),
    ]
